// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soff_skil.Data;

#nullable disable

namespace Soff_skil.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Soff_skil.Models.AcademicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DeadlineRate")
                        .HasColumnType("float")
                        .HasColumnName("deadline_rate");

                    b.Property<double>("Gpa")
                        .HasColumnType("float")
                        .HasColumnName("gpa");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("academic_data", (string)null);
                });

            modelBuilder.Entity("Soff_skil.Models.SoftSkillResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Communication")
                        .HasColumnType("float")
                        .HasColumnName("communication");

                    b.Property<double>("ContributionRate")
                        .HasColumnType("float")
                        .HasColumnName("contribution_rate");

                    b.Property<double>("CriticalThinking")
                        .HasColumnType("float")
                        .HasColumnName("critical_thinking");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("level");

                    b.Property<double>("OnTimeRate")
                        .HasColumnType("float")
                        .HasColumnName("on_time_rate");

                    b.Property<double>("ParticipationRate")
                        .HasColumnType("float")
                        .HasColumnName("participation_rate");

                    b.Property<double>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<double>("Teamwork")
                        .HasColumnType("float")
                        .HasColumnName("teamwork");

                    b.Property<double>("TimeManagement")
                        .HasColumnType("float")
                        .HasColumnName("time_management");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("soft_skill_result", null, t =>
                        {
                            t.HasCheckConstraint("CK_soft_skill_result_communication", "[communication] >= 0 AND [communication] <= 10");

                            t.HasCheckConstraint("CK_soft_skill_result_contribution_rate", "[contribution_rate] >= 0 AND [contribution_rate] <= 100");

                            t.HasCheckConstraint("CK_soft_skill_result_critical_thinking", "[critical_thinking] >= 0 AND [critical_thinking] <= 10");

                            t.HasCheckConstraint("CK_soft_skill_result_on_time_rate", "[on_time_rate] >= 0 AND [on_time_rate] <= 100");

                            t.HasCheckConstraint("CK_soft_skill_result_participation_rate", "[participation_rate] >= 0 AND [participation_rate] <= 100");

                            t.HasCheckConstraint("CK_soft_skill_result_teamwork", "[teamwork] >= 0 AND [teamwork] <= 10");

                            t.HasCheckConstraint("CK_soft_skill_result_time_management", "[time_management] >= 0 AND [time_management] <= 10");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Communication = 8.4000000000000004,
                            ContributionRate = 86.0,
                            CriticalThinking = 8.1999999999999993,
                            Level = "Good",
                            OnTimeRate = 90.0,
                            ParticipationRate = 82.0,
                            Score = 8.4100000000000001,
                            StudentId = 1,
                            Teamwork = 8.8000000000000007,
                            TimeManagement = 8.0999999999999996
                        },
                        new
                        {
                            Id = 2,
                            Communication = 7.5,
                            ContributionRate = 80.0,
                            CriticalThinking = 7.2000000000000002,
                            Level = "Average",
                            OnTimeRate = 84.0,
                            ParticipationRate = 77.0,
                            Score = 7.4199999999999999,
                            StudentId = 2,
                            Teamwork = 7.7999999999999998,
                            TimeManagement = 7.0
                        },
                        new
                        {
                            Id = 3,
                            Communication = 5.7999999999999998,
                            ContributionRate = 61.0,
                            CriticalThinking = 5.5,
                            Level = "Weak",
                            OnTimeRate = 68.0,
                            ParticipationRate = 63.0,
                            Score = 5.6699999999999999,
                            StudentId = 3,
                            Teamwork = 6.0,
                            TimeManagement = 5.2000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Communication = 9.0,
                            ContributionRate = 90.0,
                            CriticalThinking = 8.9000000000000004,
                            Level = "Good",
                            OnTimeRate = 94.0,
                            ParticipationRate = 91.0,
                            Score = 8.7899999999999991,
                            StudentId = 4,
                            Teamwork = 8.6999999999999993,
                            TimeManagement = 8.5
                        },
                        new
                        {
                            Id = 5,
                            Communication = 6.7999999999999998,
                            ContributionRate = 70.0,
                            CriticalThinking = 6.2999999999999998,
                            Level = "Average",
                            OnTimeRate = 76.0,
                            ParticipationRate = 72.0,
                            Score = 6.6100000000000003,
                            StudentId = 5,
                            Teamwork = 6.5,
                            TimeManagement = 6.9000000000000004
                        },
                        new
                        {
                            Id = 6,
                            Communication = 7.0999999999999996,
                            ContributionRate = 74.0,
                            CriticalThinking = 6.9000000000000004,
                            Level = "Average",
                            OnTimeRate = 79.0,
                            ParticipationRate = 75.0,
                            Score = 7.0800000000000001,
                            StudentId = 6,
                            Teamwork = 7.0,
                            TimeManagement = 7.4000000000000004
                        },
                        new
                        {
                            Id = 7,
                            Communication = 8.1999999999999993,
                            ContributionRate = 83.0,
                            CriticalThinking = 7.9000000000000004,
                            Level = "Good",
                            OnTimeRate = 88.0,
                            ParticipationRate = 85.0,
                            Score = 8.1099999999999994,
                            StudentId = 7,
                            Teamwork = 8.0,
                            TimeManagement = 8.4000000000000004
                        },
                        new
                        {
                            Id = 8,
                            Communication = 4.9000000000000004,
                            ContributionRate = 55.0,
                            CriticalThinking = 5.0,
                            Level = "Weak",
                            OnTimeRate = 60.0,
                            ParticipationRate = 58.0,
                            Score = 5.0,
                            StudentId = 8,
                            Teamwork = 5.2000000000000002,
                            TimeManagement = 4.7999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Communication = 6.2000000000000002,
                            ContributionRate = 73.0,
                            CriticalThinking = 6.0999999999999996,
                            Level = "Average",
                            OnTimeRate = 72.0,
                            ParticipationRate = 70.0,
                            Score = 6.3200000000000003,
                            StudentId = 9,
                            Teamwork = 6.7999999999999998,
                            TimeManagement = 6.0
                        },
                        new
                        {
                            Id = 10,
                            Communication = 7.9000000000000004,
                            ContributionRate = 82.0,
                            CriticalThinking = 7.7000000000000002,
                            Level = "Average",
                            OnTimeRate = 85.0,
                            ParticipationRate = 80.0,
                            Score = 7.8499999999999996,
                            StudentId = 10,
                            Teamwork = 8.0999999999999996,
                            TimeManagement = 7.5999999999999996
                        });
                });

            modelBuilder.Entity("Soff_skil.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("class_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassCode = "SV001",
                            Name = "Tran Van H",
                            TeacherId = 1,
                            UserId = 101
                        },
                        new
                        {
                            Id = 2,
                            ClassCode = "SV002",
                            Name = "Le Thi M",
                            TeacherId = 1,
                            UserId = 102
                        },
                        new
                        {
                            Id = 3,
                            ClassCode = "SV003",
                            Name = "Pham Quang T",
                            TeacherId = 1,
                            UserId = 103
                        },
                        new
                        {
                            Id = 4,
                            ClassCode = "SV004",
                            Name = "Vu Hoang N",
                            TeacherId = 1,
                            UserId = 104
                        },
                        new
                        {
                            Id = 5,
                            ClassCode = "SV005",
                            Name = "Bui Gia K",
                            TeacherId = 1,
                            UserId = 105
                        },
                        new
                        {
                            Id = 6,
                            ClassCode = "SV006",
                            Name = "Do Minh C",
                            TeacherId = 1,
                            UserId = 106
                        },
                        new
                        {
                            Id = 7,
                            ClassCode = "SV007",
                            Name = "Dang Thu P",
                            TeacherId = 1,
                            UserId = 107
                        },
                        new
                        {
                            Id = 8,
                            ClassCode = "SV008",
                            Name = "Nguyen Duc Q",
                            TeacherId = 1,
                            UserId = 108
                        },
                        new
                        {
                            Id = 9,
                            ClassCode = "SV009",
                            Name = "Hoang Linh Y",
                            TeacherId = 1,
                            UserId = 109
                        },
                        new
                        {
                            Id = 10,
                            ClassCode = "SV010",
                            Name = "Tran Bao U",
                            TeacherId = 1,
                            UserId = 110
                        });
                });

            modelBuilder.Entity("Soff_skil.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "teacher@school.com",
                            Name = "Nguyen Van A",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Soff_skil.Models.TeamworkData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Participation")
                        .HasColumnType("float")
                        .HasColumnName("participation");

                    b.Property<double>("PeerReview")
                        .HasColumnType("float")
                        .HasColumnName("peer_review");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("teamwork_data", (string)null);
                });

            modelBuilder.Entity("Soff_skil.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "teacher123",
                            Role = "teacher",
                            Username = "teacher"
                        },
                        new
                        {
                            Id = 101,
                            Password = "123456",
                            Role = "student",
                            Username = "sv001"
                        },
                        new
                        {
                            Id = 102,
                            Password = "123456",
                            Role = "student",
                            Username = "sv002"
                        },
                        new
                        {
                            Id = 103,
                            Password = "123456",
                            Role = "student",
                            Username = "sv003"
                        },
                        new
                        {
                            Id = 104,
                            Password = "123456",
                            Role = "student",
                            Username = "sv004"
                        },
                        new
                        {
                            Id = 105,
                            Password = "123456",
                            Role = "student",
                            Username = "sv005"
                        },
                        new
                        {
                            Id = 106,
                            Password = "123456",
                            Role = "student",
                            Username = "sv006"
                        },
                        new
                        {
                            Id = 107,
                            Password = "123456",
                            Role = "student",
                            Username = "sv007"
                        },
                        new
                        {
                            Id = 108,
                            Password = "123456",
                            Role = "student",
                            Username = "sv008"
                        },
                        new
                        {
                            Id = 109,
                            Password = "123456",
                            Role = "student",
                            Username = "sv009"
                        },
                        new
                        {
                            Id = 110,
                            Password = "123456",
                            Role = "student",
                            Username = "sv010"
                        });
                });

            modelBuilder.Entity("Soff_skil.Models.AcademicData", b =>
                {
                    b.HasOne("Soff_skil.Models.Student", "Student")
                        .WithOne("AcademicData")
                        .HasForeignKey("Soff_skil.Models.AcademicData", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Soff_skil.Models.SoftSkillResult", b =>
                {
                    b.HasOne("Soff_skil.Models.Student", "Student")
                        .WithOne("SoftSkillResult")
                        .HasForeignKey("Soff_skil.Models.SoftSkillResult", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Soff_skil.Models.Student", b =>
                {
                    b.HasOne("Soff_skil.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soff_skil.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Soff_skil.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soff_skil.Models.TeamworkData", b =>
                {
                    b.HasOne("Soff_skil.Models.Student", "Student")
                        .WithOne("TeamworkData")
                        .HasForeignKey("Soff_skil.Models.TeamworkData", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Soff_skil.Models.Student", b =>
                {
                    b.Navigation("AcademicData");

                    b.Navigation("SoftSkillResult");

                    b.Navigation("TeamworkData");
                });

            modelBuilder.Entity("Soff_skil.Models.Teacher", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Soff_skil.Models.User", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
